apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.argocd.appname }}-dependencies"
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
  project: {{ .Values.project }}
  destination:
    server: {{ .Values.cluster.address }}
    namespace: "{{ .Values.cluster.namespace }}-dependencies"
  sources:
  - repoURL: {{ .Values.values.repo_URL }}
    targetRevision: {{ .Values.values.branch }}
    ref: values
  - repoURL: {{ .Values.vault_webhook.repo_URL }}
    targetRevision: {{ .Values.vault_webhook.targetRevision }}
    chart: {{ .Values.vault_webhook.chart_name }}
    helm:
      valueFiles:
        {{- range .Values.vault_webhook.valueFiles }}
        - $values/app-values/vault-webhook/{{ . }}
        {{- end }}
      values: |
        watchNamespace: {{ .Values.cluster.namespace }}
        fullnameOverride: vault-webhook-{{ .Values.cluster.namespace }}
        serviceAccount:
          name: vault-webhook-service-account
        env:
          VAULT_ADDR: "https://secrets.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}"
          VAULT_ROLE: "{{ .Values.secrets.role }}"
        {{- if eq .Values.resourcePreset "low" }}
        resources:
          requests:
            cpu: "0"
            memory: "0"
        {{- else }}
          {{- if .Values.vault_webhook.resources }}
        resources: {{- toYaml .Values.vault_webhook.resources | nindent 10 }}
          {{- end }}
        {{- end }}
  - repoURL: {{ .Values.openbao.repo_URL }}
    targetRevision: {{ .Values.openbao.targetRevision }}
    chart: {{ .Values.openbao.chart_name }}
    helm:
      valueFiles:
        {{- range .Values.openbao.valueFiles }}
        - $values/app-values/openbao/{{ . }}
        {{- end }}
      values: |
        fullnameOverride: openbao-{{ .Release.Namespace }}
        server:
          ingress:
            annotations:
              cert-manager.io/cluster-issuer: {{ .Values.cluster.issuer }}
            hosts:
              - host: secrets.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}
            tls:
              - secretName: openbao-{{ .Values.namespaceTag }}-tls
                hosts:
                  - secrets.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}
        {{- if .Values.openbao.resources }}
        resources: {{- toYaml .Values.openbao.resources | nindent 10 }}
        {{- end }}