apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-high-speed
provisioner: disk.csi.azure.com
parameters:
  storageaccounttype: managed
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

