apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # name of the currently deploying app in argocd, this is the name that will be displayed in ArgoCD
  name: 'common01-deployer'
spec:
  project: default
  source:
    repoURL: 'https://code.europa.eu/api/v4/projects/951/packages/helm/stable'
    path: '""'   # corregido para evitar error de path vacío
    targetRevision: 2.4.0                          # version of package
    helm:
      values: |
        values:
          branch: v2.4.0                            # branch of repo with values
        resourcePreset: default                     # set to "low" to disable requests of resources
        agentList:                                  # list of all the agents to be deployed
          authorities:
            - authority01
          consumers:
            - consumer01
          providers:
            - dataprovider01
        securityContext:
          runAsUser: 0        # temporalmente root para inicialización
          runAsGroup: 0
          fsGroup: 0
        project: default                            # Project to which the namespace is attached
        namespaceTag: common01                      # identifier of deployment and part of fqdn
        domainSuffix: 192.168.49.2.nip.io          # IP DE MINIKUBE, last part of fqdn
        argocd:
          appname: common01                         # name of generated argocd app 
          namespace: argocd                         # namespace of your argocd
        cluster:
          # FQDN Fully Qualified Domain Name of your kubernetes cluster
          address: https://kubernetes.default.svc
          namespace: common01                       # where the app will be deployed
          issuer: dev-prod 
          clusterIssuer_internal: dev-prod         # issuer of certificate
          kubeStateHost: kube-prometheus-stack-kube-state-metrics.devsecopstools.svc.cluster.local:8080
        secrets:
          secretEngine: example                     # name of the kv secret engine that will be created in OpenBao
          role: example-role                        # name of the role that will be created in OpenBao
        kafka:
          ha: true                                  # true creates 3 replicas of each component, false creates 1 of each
          topic:
            autocreate: true                        # set to true to create topics automatically
        mailpit:
          enabled: true                             # set to true to activate mailpit
        monitoring:
          enabled: true                             # set to true to enable monitoring features
        certificates:
          elkCA:
           enabled: true
           secretName: elk-ca-common01-tls
        resources:                                  # <-- sección añadida
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"

    # Name of the helm chart to deploy
    chart: common_components
  destination:
    # FQDN Fully Qualified Domain Name of your kubernetes cluster
    server: 'https://kubernetes.default.svc'
    # Name of the Kubernetes NameSpace in which the Common Tools will be deployed
    namespace: common01

